### ISSUE TITLE
`Roll your own` redirects to Sign In with username and password

### ISSUE THREAD

**Issue by estensen** [sanity-io/sanity-template-gatsby-portfolio#1]
I'm trying to use this template to create a Sanity and Gatsby project.
Clicking the link in the README I'm redirected to login with username and password.
But I signed up with Github and don't have a username and password and there is no way of adding it under [account management](https://manage.sanity.io/account)
How can I use this template to create a new project?

This is also the case for these templates:
sanity-template-nextjs-landing-pages
sanity-template-gatsby-portfolio

**Comment by mariuslundgard** [comment]
Hey @estensen, we’re working on a new feature that’s not quite ready yet. We’re sorry for the inconvenience of having stumbled across this while it’s not ready and not communicated. Will make a note in the README asap. Stay tuned!

**Comment by kmelve** [comment]
Closing this since we have launched [sanity.io/create](https://www.sanity.io/create) where this template can be deployed.
