### ISSUE TITLE
White page on Localhost:8000

### ISSUE THREAD

**Issue by zer0below** [sanity-io/sanity-template-gatsby-portfolio#4]
Hi I followed your instructions, Im in the part of displaying the data in frontend which is http://localhost:8000/, after i execute this command "npm run graphql-deploy"
this error occurs please see screenshot below:
![image](https://user-images.githubusercontent.com/38272278/60158270-5347c300-9823-11e9-9f8c-9faad45db4fe.png)

and here's the error logs please see screenshot
![image](https://user-images.githubusercontent.com/38272278/60158366-87bb7f00-9823-11e9-8565-ffafde77bde6.png)

and the display in http://localhost:8000/ is blank white page 

Thankyou and more power

**Comment by kmelve** [comment]
Thanks for reporting! For the `npm run graphql-deploy` issue, it seems that you're running it in the `/web` folder. Try running it in the root folder. If you run `npm run` you can see the available commands in each given folder in the project.

We'll take a closer look at the second issue.

**Comment by zer0below** [comment]
Hi have already done that please see screenshot
![image](https://user-images.githubusercontent.com/38272278/60160288-9dcb3e80-9827-11e9-8180-5e3eddff7701.png)

**Comment by zer0below** [comment]
but the local http://localhost:3333/ is working

**Comment by thomax** [comment]
@zer0below any chance you could join our [Slack](https://slack.sanity.io/)? Figuring this one out will be a lot easier w/snappy back and forth communication

**Comment by zer0below** [comment]
Hi i close everything and re-run again including the npm run graphql-deploy and i get this error
![image](https://user-images.githubusercontent.com/38272278/60167609-fe617800-9835-11e9-9d39-a0602d2f958d.png)

**Comment by thomax** [comment]
1. Are you sure `tagline` is a field on the `SiteSettings` type?
2. If yes, try running `sanity graphql deploy`

**Comment by thomax** [comment]
Again, I'd very much like to help you get this running, but this is not an issue with the template source code. Would be much easier to figure this out in our [Slack community](https://slack.sanity.io/).

**Comment by zer0below** [comment]
> 1. Are you sure `tagline` is a field on the `SiteSettings` type?
> 2. If yes, try running `sanity graphql deploy`

![image](https://user-images.githubusercontent.com/38272278/60168253-11287c80-9837-11e9-8884-c76dd99f16a1.png)
![image](https://user-images.githubusercontent.com/38272278/60168354-40d78480-9837-11e9-8d05-54aabb9e32fd.png)

2.

**Comment by thomax** [comment]
Did you start this project by using https://www.sanity.io/create?template=sanity-io%2Fsanity-template-gatsby-portfolio or did you go your own by cloning the repo directly from https://github.com/sanity-io/sanity-template-gatsby-portfolio ?

**Comment by zer0below** [comment]
> Did you start this project by using https://www.sanity.io/create?template=sanity-io%2Fsanity-template-gatsby-portfolio or did you go your own by cloning the repo directly from https://github.com/sanity-io/sanity-template-gatsby-portfolio ?

I created my own https://www.sanity.io/create?template=sanity-io%2Fsanity-template-gatsby-portfolio

**Comment by zer0below** [comment]
> @zer0below any chance you could join our [Slack](https://slack.sanity.io/)? Figuring this one out will be a lot easier w/snappy back and forth communication

have already posted the issue there

**Comment by thomax** [comment]
Right. Let's move there https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1561545566401100?thread_ts=1561543028.395000&cid=C9Z7RC3V1

**Comment by zer0below** [comment]
unfortunately no one answering my question =(
